const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Anchor,
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Pin,
		C3.Behaviors.Physics,
		C3.Behaviors.scrollto,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.PlatformInfo,
		C3.Plugins.LocalStorage,
		C3.Plugins.Arr,
		C3.Behaviors.skymen_BoundToViewport,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Plugins.System.Exps.int,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Physics.Acts.SetSteppingMode,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Sin.Acts.SetMovement,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Behaviors.Physics.Acts.CreateRevoluteJoint,
		C3.Plugins.Sprite.Cnds.PickTopBottom,
		C3.Plugins.TiledBg.Acts.ZMoveToObject,
		C3.Behaviors.Physics.Acts.SetDensity,
		C3.Behaviors.Physics.Acts.SetFriction,
		C3.Behaviors.Physics.Acts.SetElasticity,
		C3.Behaviors.Physics.Acts.SetLinearDamping,
		C3.Behaviors.Physics.Acts.SetAngularDamping,
		C3.Behaviors.Physics.Acts.SetBullet,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Physics.Acts.SetAngularVelocity,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Physics.Exps.VelocityX,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.skymen_BoundToViewport.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.TiledBg.Cnds.IsVisible,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.System.Cnds.LayerVisible
	];
};
self.C3_JsPropNameTable = [
	{Anchor: 0},
	{TiledBackground: 0},
	{Tween: 0},
	{btnSound: 0},
	{Sine: 0},
	{GameLogo: 0},
	{btnFullscreen: 0},
	{btnGo: 0},
	{btnLeft: 0},
	{btnRight: 0},
	{CarScence: 0},
	{LogoCars: 0},
	{btnClose: 0},
	{btnStudy: 0},
	{studyBoard: 0},
	{logoRotate: 0},
	{boardLevel: 0},
	{btnHome: 0},
	{Level: 0},
	{StartX: 0},
	{btnLevel: 0},
	{SpriteFont: 0},
	{Sprite: 0},
	{Pin: 0},
	{Block: 0},
	{Move: 0},
	{Physics: 0},
	{ScrollTo: 0},
	{car2: 0},
	{TiledBackground2: 0},
	{TiledBackground3: 0},
	{wheel2: 0},
	{moved: 0},
	{darging: 0},
	{block1: 0},
	{btnStartCar: 0},
	{cloud: 0},
	{FinishPoint: 0},
	{End: 0},
	{flor: 0},
	{startx: 0},
	{buoys: 0},
	{btnOverHome: 0},
	{LoseBoard: 0},
	{Sprite2: 0},
	{boardWin: 0},
	{btnOverNext: 0},
	{btnOverRetry: 0},
	{block2: 0},
	{block3: 0},
	{block4: 0},
	{block5: 0},
	{block6: 0},
	{block7: 0},
	{buoys2: 0},
	{TiledBackground4: 0},
	{block8: 0},
	{block9: 0},
	{block10: 0},
	{block11: 0},
	{bloc47: 0},
	{block12: 0},
	{block13: 0},
	{block14: 0},
	{block15: 0},
	{block16: 0},
	{block17: 0},
	{block18: 0},
	{block19: 0},
	{block20: 0},
	{block21: 0},
	{block22: 0},
	{block23: 0},
	{block24: 0},
	{block25: 0},
	{block26: 0},
	{block27: 0},
	{block28: 0},
	{block29: 0},
	{block30: 0},
	{block31: 0},
	{block32: 0},
	{block33: 0},
	{block34: 0},
	{block35: 0},
	{block36: 0},
	{block37: 0},
	{block38: 0},
	{block39: 0},
	{block40: 0},
	{block41: 0},
	{block42: 0},
	{block43: 0},
	{block44: 0},
	{block45: 0},
	{block46: 0},
	{block48: 0},
	{block49: 0},
	{block50: 0},
	{block51: 0},
	{block52: 0},
	{block53: 0},
	{block54: 0},
	{block55: 0},
	{block56: 0},
	{block57: 0},
	{block58: 0},
	{thorw: 0},
	{btnRetry: 0},
	{btnIdea: 0},
	{counterHint: 0},
	{Text: 0},
	{TiledBackground5: 0},
	{Audio: 0},
	{Browser: 0},
	{Touch: 0},
	{PlatformInfo: 0},
	{LocalStorage: 0},
	{Levels: 0},
	{BoundToViewport: 0},
	{Fblocks: 0},
	{Sound: 0},
	{Car: 0},
	{AddXLevel: 0},
	{Hint: 0},
	{TimerCar: 0},
	{Return: 0},
	{x: 0},
	{win: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	btnSound: class extends self.ISpriteInstance {},
	GameLogo: class extends self.ISpriteInstance {},
	btnFullscreen: class extends self.ISpriteInstance {},
	btnGo: class extends self.ISpriteInstance {},
	btnLeft: class extends self.ISpriteInstance {},
	btnRight: class extends self.ISpriteInstance {},
	CarScence: class extends self.ISpriteInstance {},
	LogoCars: class extends self.ISpriteInstance {},
	btnClose: class extends self.ISpriteInstance {},
	btnStudy: class extends self.ISpriteInstance {},
	studyBoard: class extends self.ISpriteInstance {},
	logoRotate: class extends self.ISpriteInstance {},
	boardLevel: class extends self.ISpriteInstance {},
	btnHome: class extends self.ISpriteInstance {},
	btnLevel: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Block: class extends self.ISpriteInstance {},
	car2: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	wheel2: class extends self.ISpriteInstance {},
	block1: class extends self.ISpriteInstance {},
	btnStartCar: class extends self.ISpriteInstance {},
	cloud: class extends self.ISpriteInstance {},
	FinishPoint: class extends self.ISpriteInstance {},
	flor: class extends self.ISpriteInstance {},
	buoys: class extends self.ISpriteInstance {},
	btnOverHome: class extends self.ISpriteInstance {},
	LoseBoard: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	boardWin: class extends self.ISpriteInstance {},
	btnOverNext: class extends self.ISpriteInstance {},
	btnOverRetry: class extends self.ISpriteInstance {},
	block2: class extends self.ISpriteInstance {},
	block3: class extends self.ISpriteInstance {},
	block4: class extends self.ISpriteInstance {},
	block5: class extends self.ISpriteInstance {},
	block6: class extends self.ISpriteInstance {},
	block7: class extends self.ISpriteInstance {},
	buoys2: class extends self.ISpriteInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	block8: class extends self.ISpriteInstance {},
	block9: class extends self.ISpriteInstance {},
	block10: class extends self.ISpriteInstance {},
	block11: class extends self.ISpriteInstance {},
	bloc47: class extends self.ISpriteInstance {},
	block12: class extends self.ISpriteInstance {},
	block13: class extends self.ISpriteInstance {},
	block14: class extends self.ISpriteInstance {},
	block15: class extends self.ISpriteInstance {},
	block16: class extends self.ISpriteInstance {},
	block17: class extends self.ISpriteInstance {},
	block18: class extends self.ISpriteInstance {},
	block19: class extends self.ISpriteInstance {},
	block20: class extends self.ISpriteInstance {},
	block21: class extends self.ISpriteInstance {},
	block22: class extends self.ISpriteInstance {},
	block23: class extends self.ISpriteInstance {},
	block24: class extends self.ISpriteInstance {},
	block25: class extends self.ISpriteInstance {},
	block26: class extends self.ISpriteInstance {},
	block27: class extends self.ISpriteInstance {},
	block28: class extends self.ISpriteInstance {},
	block29: class extends self.ISpriteInstance {},
	block30: class extends self.ISpriteInstance {},
	block31: class extends self.ISpriteInstance {},
	block32: class extends self.ISpriteInstance {},
	block33: class extends self.ISpriteInstance {},
	block34: class extends self.ISpriteInstance {},
	block35: class extends self.ISpriteInstance {},
	block36: class extends self.ISpriteInstance {},
	block37: class extends self.ISpriteInstance {},
	block38: class extends self.ISpriteInstance {},
	block39: class extends self.ISpriteInstance {},
	block40: class extends self.ISpriteInstance {},
	block41: class extends self.ISpriteInstance {},
	block42: class extends self.ISpriteInstance {},
	block43: class extends self.ISpriteInstance {},
	block44: class extends self.ISpriteInstance {},
	block45: class extends self.ISpriteInstance {},
	block46: class extends self.ISpriteInstance {},
	block48: class extends self.ISpriteInstance {},
	block49: class extends self.ISpriteInstance {},
	block50: class extends self.ISpriteInstance {},
	block51: class extends self.ISpriteInstance {},
	block52: class extends self.ISpriteInstance {},
	block53: class extends self.ISpriteInstance {},
	block54: class extends self.ISpriteInstance {},
	block55: class extends self.ISpriteInstance {},
	block56: class extends self.ISpriteInstance {},
	block57: class extends self.ISpriteInstance {},
	block58: class extends self.ISpriteInstance {},
	thorw: class extends self.ISpriteInstance {},
	btnRetry: class extends self.ISpriteInstance {},
	btnIdea: class extends self.ISpriteInstance {},
	counterHint: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Levels: class extends self.IArrayInstance {},
	Fblocks: class extends self.ISpriteInstance {}
}